# Generated by Django 5.0.3 on 2026-04-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='diagnosis',
            field=models.TextField(blank=True, help_text="Doctor's diagnosis"),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional doctor notes'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(help_text='e.g., 2 tablets twice daily', max_length=100),
        ),
    ]
