# Generated by Django 5.0.3 on 2026-04-27 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_patient_address_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('liquid', 'Liquid'), ('powder', 'Powder'), ('capsules', 'Capsules'), ('raw_herbs', 'Raw Herbs')], default='capsules', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('ml', 'ml'), ('liters', 'Liters'), ('g', 'g'), ('kg', 'kg'), ('pieces', 'Pieces'), ('bottles', 'Bottles'), ('bundles', 'Bundles')], default='pieces', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
