# Generated by Django 5.0.3 on 2026-04-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_medicine_category_medicine_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='total_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Maximum stock capacity (100% level)'),
        ),
    ]
