# Generated by Django 5.0.3 on 2026-05-01 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_visit_paid_amount_visit_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=50)),
                ('ticket_number', models.CharField(max_length=20)),
                ('medicine_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='clinic.visit')),
            ],
        ),
    ]
