# Generated by Django 5.2.12 on 2026-05-05 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='medicine_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='total',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinic.receipt')),
            ],
        ),
    ]
