# Generated by Django 5.2.12 on 2026-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='doctor_notes',
            field=models.TextField(blank=True, help_text="Doctor's additional notes during follow-up"),
        ),
        migrations.AddField(
            model_name='followup',
            name='re_diagnosis',
            field=models.TextField(blank=True, help_text="Doctor's re-diagnosis during follow-up"),
        ),
        migrations.AddField(
            model_name='followup',
            name='reassigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='reassigned_by',
            field=models.CharField(blank=True, help_text='Receptionist who reassigned', max_length=100),
        ),
        migrations.AddField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('pending_reassign', 'Pending Reassignment'), ('reassigned', 'Reassigned to Doctor'), ('in_progress', 'Doctor In Progress'), ('completed', 'Completed')], default='pending_reassign', max_length=20),
        ),
    ]
