# Generated by Django 5.2.12 on 2026-05-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_followup_completed_at_followup_doctor_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='total_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Maximum stock capacity (100% level). Must be >= stock_quantity.'),
        ),
    ]
